<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FsCheck"/>
    <PackageReference Include="FsCheck.Xunit"/>
    <PackageReference Include="xunit"/>
    <PackageReference Include="xunit.runner.visualstudio"/>
    <PackageReference Include="FluentAssertions"/>
    <PackageReference Include="NSubstitute"/>
    <PackageReference Include="Microsoft.NET.Test.Sdk"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\RateLimiter.Infrastructure\RateLimiter.Infrastructure.csproj" />
  </ItemGroup>

</Project>
